### ISSUE TITLE
ugtrain needs more fame - still too unknown

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#11]
Contributors are required who
- don't abuse this tool against Steam or any commercial game right away
- have good Linux and command line skills
- test this tool against FOSS games
- promote this tool - placing articles on better known websites works best (fame hijacking)
- have enough passion for Linux game cheating to contribute regularly
- help to improve documentation and make this tool simpler

Not enough people watch or like the videos, not enough watchers or stargazers on GitHub,...

**Comment by sriemer** [comment]
Also looking for public speaking possibilities.
* Berlin Hack and Tell already knows about ugtrain -> no outcome
* LinuxTag in Berlin has been cancelled for 2015
* no response from the FOSDEM organizers -> trying again when it's time for call for papers

**Comment by sriemer** [comment]
Any recommendations how to promote ugtrain better?

**Comment by sriemer** [comment]
`scanmem` and `ugtrain` have been mentioned on UnKnoWnCheaTs. :+1: 

https://www.unknowncheats.me/forum/tags/scanmem.html
http://www.unknowncheats.me/forum/tags/ugtrain.html

**Comment by Mykezero** [comment]
I've been looking for another project to contribute to on weekends, and I'd love to help improve the program documentation.

**Comment by sriemer** [comment]
Thanks, I really appreciate that. I try to write down the TODOs a bit more in form of GitHub issues as I can track them better this way. In the ugtrain GitHub organization I could add contributors and assign them later on to GitHub issues. E.g. man pages are required and some files still need to be converted into Markdown files. Just tell me if you need any help or info.

**Comment by Mykezero** [comment]
Alright, sounds good!

**Comment by flarn2006** [comment]
I don't really think this issue can be described as a bug.

**Comment by sriemer** [comment]
As a bug it has better visibility. And there is a bug in the promotion methods used so far. Gaming tracks are also not really interested in this. Showing these methods to potential enemies is also not the best.

**Comment by sriemer** [comment]
Placing a link to ugtrain in the Reverse Engineering Subreddit worked out very well.

https://www.reddit.com/r/ReverseEngineering/comments/3lwjyw/ugtrain_universal_elite_game_trainer_for_the/

![ugtrain_traffic](https://cloud.githubusercontent.com/assets/1803210/10176348/73746552-66f4-11e5-8999-08ec604d42ac.png)

Sharing the traffic graph with 690 visits at its peak. Two more watchers, nine more stargazers.

**Comment by sriemer** [comment]
Got mentioned in the LinuxGameCast EP162 because of the Reddit link:

http://linuxgamecast.com/2015/09/linuxgamecast-weekly-ep162-bad-vives/

**Comment by sriemer** [comment]
Proposed a talk in German about Linux Game Cheating to the committer conf 2015 in Essen/Germany:

https://committerconf.de/2015/sessions/linux-game-cheating-ein-legaler-einblick

Ticket buyers vote what to see but I don't really think that this gets voted high enough.

**Comment by sriemer** [comment]
It happened like expected: My talk hasn't been accepted for CommitterConf. 1000 km less to travel.

**Comment by sriemer** [comment]
I'm ready for the upcoming Linux events. Chemnitzer Linux-Tage comes next. If people don't let me present, then I'll do promotion this way.
<table><tr><td>
<img src="https://cloud.githubusercontent.com/assets/1803210/13511922/c76174c0-e197-11e5-81ed-35fc1b576c87.jpg" width=300" /></td><td>
<img src="https://cloud.githubusercontent.com/assets/1803210/13511921/c75de6e8-e197-11e5-997d-cf7db2c4422a.jpg" width=300" />
</td></tr></table>

**Comment by sriemer** [comment]
Fuck that! Starting treating ugtrain as my personal game cheating research project.
