### ISSUE TITLE
Announce: Moved ugtrain to ugtrain organization

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#18]
Please adapt your .git/config. Replace "sriemer" with "ugtrain"!

Having ugtrain in an organization has some advantages like having the possibility to place the logo and the mailing list email address to the org. Also teams can be created. I've created "Committers" and "Contributors" with the appropriate privileges. This way it's better to show the contributors and it feels more like contributing to a project than to the stuff of another person. This way we can also assign contributors to issues. It is also easy to invite contributors.

sriemer/ugtrain forwards to ugtrain/ugtrain.

Any thoughts or comments?

**Comment by sriemer** [comment]
No that @Mortezaipo is in the "Contributors" team I can assign him to issues or he should also be able to assign himself. :-)

**Comment by sriemer** [comment]
People should have noticed. So closing.

**Comment by Mortezaipo** [comment]
Thanks a lot. I will do my best.
