### ISSUE TITLE
Trouble with Warzone2100 adaption on Ubuntu 14.04 32-bit with 0.2 release

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#20]
From @tigefa4u:
did i miss this
[![asciicast](https://asciinema.org/a/24943.png)](https://asciinema.org/a/24943)
boom error :hushed:

**Comment by sriemer** [comment]
Hi @tigefa4u,
as you wrote me in a scanmem issue, you use Ubuntu 14.04 Trusty. The Warzone 2100 configs have been tested against that Ubuntu version which use warzone2100 3.1-rc1.

Is it possible that you have a 64-bit system and 64-bit OS?

Is it possible that you didn't copy the file `_common_adapt.sh` to `~/.ugtrain/adapt/`?

Please run ``~/.ugtrain/adapt/warzone2100_adapt32.sh `which warzone2100` DEBUG`` and paste its output here.

**Comment by sriemer** [comment]
This is my output on my 64-bit Ubuntu 14.04 64-bit:
````
$ ~/.ugtrain/adapt/warzone2100_adapt32.sh `which warzone2100` DEBUG
objdump -D /usr/games/warzone2100
echo $CODE | grep \<_Znwj@plt\> -B 2 -A 1
echo $FUNC_CALLS | grep -A 2 0x2fc,
````
No `_Znwj()` call (32-bit C++ `new` operator) has been found as I use a 64-bit system and also the warzone2100 binary is 64-bit this way.
I test the 32-bit configs with live-USBs or with a 32-bit EeePC.

Lets check the 64-bit debug output:
````
$ ~/.ugtrain/adapt/warzone2100_adapt64.sh `which warzone2100` DEBUG
objdump -D /usr/games/warzone2100
echo $CODE | grep \<_Znwm@plt\> -B 2 -A 1
echo $FUNC_CALLS | grep -A 3 0x360,
   b167d:	bf 60 03 00 00       	mov    $0x360,%edi
   b1682:	41 89 c6             	mov    %eax,%r14d
   b1685:	e8 e6 6f fb ff       	callq  68670 <_Znwm@plt>
   b168a:	89 ea                	mov    %ebp,%edx
CODE_CALL:
   b1685:	e8 e6 6f fb ff       	callq  68670 <_Znwm@plt>
CODE_ADDR:
b168a
echo $FUNC_CALLS | grep -A 3 0x1a8,
  1e4368:	bf a8 01 00 00       	mov    $0x1a8,%edi
  1e436d:	e8 fe 42 e8 ff       	callq  68670 <_Znwm@plt>
  1e4372:	48 89 c5             	mov    %rax,%rbp
--
  1ee4ed:	bf a8 01 00 00       	mov    $0x1a8,%edi
  1ee4f2:	89 44 24 60          	mov    %eax,0x60(%rsp)
  1ee4f6:	e8 75 a1 e7 ff       	callq  68670 <_Znwm@plt>
  1ee4fb:	8b 54 24 3c          	mov    0x3c(%rsp),%edx
CODE_CALL:
  1ee4f6:	e8 75 a1 e7 ff       	callq  68670 <_Znwm@plt>
CODE_ADDR:
1ee4fb
2;Droid;0x360;0xb168a;Structure;0x1a8;0x1ee4fb
````
Extracting the right code addresses of the 64-bit C++ constructors worked. For Droid a unique allocation has been found and for Structure there are two. We use the second one.

**Comment by sriemer** [comment]
TODOs for myself:
* run the adaption script in debug mode automatically when adaption fails
* add an error message if no such function calls can be found at all

**Comment by tigefa4u** [comment]
sugeng@tigefa:~$ ~/.ugtrain/adapt/warzone2100_adapt32.sh `which warzone2100` DEBUG
objdump -D /usr/games/warzone2100
echo -e $CODE | grep \<_Znwj@plt\> -B 2 -A 1
echo -e $FUNC_CALLS | grep -A 2 0x2fc,
-e    9bd7d:	c7 04 24 fc 02 00 00 	movl   $0x2fc,(%esp)
   9bd84:	89 c7                	mov    %eax,%edi
   9bd86:	e8 35 14 fb ff       	call   4d1c0 <_Znwj@plt>
-e CODE_CALL:
   9bd86:	e8 35 14 fb ff       	call   4d1c0 <_Znwj@plt>
-e CODE_ADDR:
9bd86
echo -e $FUNC_CALLS | grep -A 2 0x16c,

**Comment by sriemer** [comment]
When did you clone ugtrain?

This is not the most recent version. Please use latest Git HEAD from the master branch.

Did you check out version 0.2?

Sorry, it is already a year old, there are 163 commits since then and it would be time for the next release. The intention was finding and cheating at as many FOSS games as possible. But I had to improve the dynamic memory handling, discovery, adaption as well as PIE support on the way. I also had to introduce PIC support.
This tool is still under heavy development. Many methods have to be researched first as they are unique on Linux and crackers usually don't tell you how they do it.

The missing commit which causes your trouble is the following:

ffb3e58673bf adapt: common: remove the '-e' option from echo

So please use latest Git HEAD from master.

**Comment by tigefa4u** [comment]
working now with master archive, before is from releases page :+1:
thank very much for your time reply this. :heart_eyes:

**Comment by sriemer** [comment]
Thanks for reporting! I'll check Ubuntu 14.04 32-bit from a live-USB again myself.

**Comment by sriemer** [comment]
I've checked with the Ubuntu 14.04 i386 live-USB. Adaption works with latest ugtrain. Only the **SFuncPtr** pointing to **0xa8** has to be changed to point to **0xa4**. I can't adapt value entries yet. Otherwise, your factories won't be able to build fast and your research facilities won't be able to reseach fast. This must be caused by compiler differences between Precise and Trusty. x86_64 isn't affected.

**Comment by sriemer** [comment]
I've changed the 32-bit config of warzone2100 to use Ubuntu 14.04 Trusty as the example as well. This is more common. So you could use this one even right away without any adaption now.

See commit e53bc3d16fd2eede783fa31edf9abdff85d5141a.
