### ISSUE TITLE
Need bash completion for config files in . and ~/.ugtrain/

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#22]
Would be much easier and better if there would be bash completion for the config files stored in ./ and ~/.ugtrain/.

**Comment by sriemer** [comment]
Sorry, I forgot to mention that only .conf files are used and that ugtrain searches in the current directory first. My commit handles that. **Could you please review it?**

What's next is the distribution via autotools. I've found the following article regarding this:
http://www.swansontec.com/bash-completion.html

**Comment by Mortezaipo** [comment]
I checked that. That was perfect. I will update autotools.

**Comment by sriemer** [comment]
I've implemented this with the referenced three commits.
http://www.swansontec.com/bash-completion.html helped a lot and I had a close look at the other bash completion scripts in /etc/bash_completions.d/ and /usr/share/bash_completion/completions/.

Now we have bash completion. :-)
