### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ugtrain/ugtrain#25]
Would you like to add more error handling for return values from functions like the following?
- [atexit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/atexit.html "Register a function to run at process termination") ⇒ [main](https://github.com/ugtrain/ugtrain/blob/71de9ebb7e265b966405a854cddb74e6aeb072f1/src/ugtrain.cpp#L835)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [prepare_getch](https://github.com/ugtrain/ugtrain/blob/814f0ac3b8412dd82e7f1e34fa0a65ffbd60755c/src/lib/getch_l.c#L34)

**Comment by sriemer** [comment]
Thanks for reporting! This is fixed now.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for [your software](https://github.com/ugtrain/ugtrain/commit/f68698616a3392e31c16d204b7a8b4e7aba2f819#commitcomment-13363240 "Another update candidate")?

**Comment by sriemer** [comment]
Is important. Should be done. The idea is to automate that with Travis-CI and Coverity.

**Comment by elfring** [comment]
Unfortunately, I got the impression that a service like "[Coverity Scan](https://scan.coverity.com/ "Static source code analysis")" does also not indicate similar open issues. Other development tools can help you more eventually.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by sriemer** [comment]
I'd like to avoid adding more dependencies and making the build more complex. C++ is only in there for convenience. Otherwise, I'm fine with functional programming.

**Comment by elfring** [comment]
Can it help to delegate any software maintenance tasks to dedicated development tools?
