### ISSUE TITLE
gentoo ebuilds

### ISSUE THREAD

**Issue by elitak** [ugtrain/ugtrain#33]
I made a quick layman overlay to provide packaging for gentoo:
https://github.com/elitak/ugtrain-overlay

Let me know if anything needs changing.

**Comment by sriemer** [comment]
Thanks, sorry for the delay! I'm back from vacation and I'll look at this shortly.

**Comment by sriemer** [comment]
Looks great. Thanks! But I consider the versions 0.1 and 0.2 very much deprecated by now. I'll release v0.3 soon. Would be cool if you could report back some feedback using ugtrain.
