### ISSUE TITLE
Release v0.3 and provide Debian packages for easy download/install

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#35]
The version v0.3 has to be finally released as the last "coiled rattlesnake" release in terms of usability. It will be the "dynmem PIC release" as it supports dynamic memory allocations from within a library. With a bit of anti-abuse it should be safe making ugtrain easy testable by providing Debian packages for avoiding to compile manually. The final Debian packages can be uploaded to Sourceforge.

**Comment by sriemer** [comment]
Ubuntu users can get the ugtrain v0.3 package from my game-cheating PPA now:

https://launchpad.net/~s-parschauer/+archive/ubuntu/game-cheating

**Comment by tigefa4u** [comment]
awesome :sparkling_heart: :heart_eyes:

**Comment by sriemer** [comment]
Debian packages are also available from here now: https://sourceforge.net/projects/ugtrain/files/
