### ISSUE TITLE
Split documentation into a beginners and an expert/devel doc

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#37]
The documentation contains too many technical details. A beginner doesn't want to know all the tricks which are possible or the nifty implementation details. He usually only wants to know how to do the most common tasks and doesn't really want to know how it works internally. Stuff has to be made as simple as possible. If it doesn't work fast enough or not as described, then the beginners usually don't use the tool or if we're lucky ask for help.

Developers and experts want to know how stuff is implemented and have very special use-cases in mind. With that they might well have ideas for improvement and contribution in mind. But these are usually also able to read code to get the required information themselves and definitely ask for help if they want to know something very special.

So the focus should be on the beginners.

**Comment by mashu** [comment]
Would be nice to have a tutorial, how to use the tool to modify value (i.e minerals) in a modern game, running on system with ASLR and PIE. I am running GNU/Linux Debian (kernel 4.14), I think I followed up documentation and tried everything, but I always end up narrowing to 0 matches with scanmem.

**Comment by sriemer** [comment]
ugtrain is meant for: If scanmem can find it, ugtrain should be able to freeze it.
The default scan data type of scanmem is "int". If you have no idea what to look for use type "number" with a small range for floats. If 1300 is displayed, try 1299..1301. Floats are often used in games. endless-sky even uses doubles.
Local memory search doesn't work for multiplayer and online games where values are stored on the server.
Some commercial games also hide memory values by XOR ing random values with them. Then sometimes only a temporary value for the display is found and a gdb watchpoint can be used to find the code changing that value. In any way disassembly analysis is required then. There is a gdb frontend project called PINCE on Github for that method now.

At which game are you trying to cheat?

**Comment by mashu** [comment]
I was trying to add minerals in Stellaris. In single player "not iron-mode" player can type ` and minerals 100. I want to know if I can do the same with ugtrain+scanmem to understand if it works. I already tried ranges like 200.0...216.0 because mineral income is 15.25, but game shows whole number.

**Comment by sriemer** [comment]
Steam stuff always requires networking, Steam spies on you. Guess where interesting memory values are stored. On the server. I can't help you here and this is the wrong Github issue for this. Start with FOSS games like e.g. Chromium B.S.U. if you want to see ugtrain in action.

**Comment by sriemer** [comment]
Feature dismissed.
