### ISSUE TITLE
Space in process names

### ISSUE THREAD

**Issue by btn21** [ugtrain/ugtrain#48]
It seems ugtrain currently doesn't allow for spaces in process names.

If there's a space in the process name, you get error:
"First line doesn't contain a valid process name!"

**Comment by sriemer** [comment]
The reason is that `execvp()` cannot handle spaces. So I would always have to call a shell which can be insecure and slow again.
For what exactly do you need this? Which game/application?

**Comment by sriemer** [comment]
This is fixed. Thanks for reporting!
