### ISSUE TITLE
TODO: Build, test, and upload new distro packages with v0.4

### ISSUE THREAD

**Issue by sriemer** [ugtrain/ugtrain#69]
Debian, Ubuntu, openSUSE, ...

**Comment by sriemer** [comment]
Older Ubuntu LTSS also required explicit `autoconf` and `automake` build depends.

**Comment by sriemer** [comment]
Ugtrain in private debian project on salsa: https://salsa.debian.org/spars-guest/ugtrain
Ugtrain Ubuntu game-cheating PPA source: https://github.com/sriemer/ugtrain-debian

There are build scripts in the `script` branch.

**Comment by sriemer** [comment]
Both, the Debian unstable (0.4-0sp1) and the Ubuntu Bionic package (0.4.0-sp2.3), work perfectly on Bionic.

First run:
```
$ ugtrain --help
[ugt] First run of ugtrain detected:
[ugt] + Creating "/home/sebastian/.ugtrain/".
[ugt] + Copying examples to "/home/sebastian/.ugtrain/".
[ugt] Checking if find is available: yes
[ugt] Checking if gunzip is available: yes
[ugt] + Extracting examples in "/home/sebastian/.ugtrain/".

ugtrain is the universal elite game trainer
...
```

Adaptation of the main examples is working fine. Also the other examples developed for Bionic are working fine.

**Comment by sriemer** [comment]
@greizgh and @elitak you might want to update packaging as well.

Sorry that `v0.4` took so long due to difficult strategic decision how to proceed with development. Trying to release once per year with less new features per release in the future.

This version contains lots of cool new features. See: https://github.com/ugtrain/ugtrain/releases

**Comment by sriemer** [comment]
Packaging fixes pushed to `v0.4.1`.

**Comment by greizgh** [comment]
@sriemer I just checked and the package still builds fine on archlinux.

**Comment by sriemer** [comment]
Thanks, guys. I've built the openSUSE packages now and fixed the 64 bit CPU detection with testing against SUSE OBS: https://build.opensuse.org/package/show/home:sparschauer/ugtrain

Two further patches pushed to `0.4.y` branch for this.
The work here is done. So closing.
