### ISSUE TITLE
Information to the issue #83

### ISSUE THREAD

**Issue by kswit** [ugtrain/ugtrain#84]
Here is "/proc/pid/maps" for Debugger_ 3_16_Recoded_DOD_Edition => [maps](https://termbin.com/jedd)
Ubuntu 22.04.1 LTS and AMD ryzen 5 2600x

**Comment by sriemer** [comment]
Thanks, Wine is not supported yet. Wine explains the unusual memory regions. I don’t have any capacity to implement this. So closing. Sorry.
